# Generated by Django 4.2.9 on 2024-01-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Context',
            new_name='context',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='Message content',
            new_name='message_content',
        ),
    ]
